Task1 c:
alvls/mp1-2019-2 pull request #14
Opened 2019-09-19 16:56 UTC by fyrirvari

2019-09-20 09:33 UTC, alvls commented
Никита, отлично!

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,5
Штраф: | 0,0
__Итого:__ | 6,5

2019-09-22 07:51 UTC, alvls requested changes

2019-09-22 07:51 UTC, alvls commented on klevtsov_nm/task1'/Source.c
> +	if ((difWord == 1) && (difNum == 1))
Условие на ход короля неверно.

2019-09-22 07:51 UTC, alvls commented on klevtsov_nm/task1'/Source.c
> +		scanf("%s", &K1);
Функция scanf должна получить адреса переменных - это вы учли. Но особенность языка Си в том, что имя массива уже является его адресом, поэтому для ввода строки в массив char можно писать 

    scanf("%s", K1);

2019-09-22 07:51 UTC, alvls commented on klevtsov_nm/task1'/Source.c
> +	difWord = fabs((int)(word1)- (int)word2);
Добавьте пробел перед минусом

2019-09-22 07:51 UTC, alvls commented on klevtsov_nm/task1'/Source.c
> +		num2 = (int)K2[1]-48;
В этих двух строках добавьте пробелы вокруг минуса

2019-09-22 07:54 UTC, alvls commented
Никита,
1. Исправьте одну ошибку и несколько мелочей по оформлению.
2. В целом хороший код, но его можно еще улучшить. Подумайте, как можно "избавиться" от повторяющихся фрагментов кода в операторе switch.

2019-09-22 11:25 UTC, alvls commented
То, что уменьшился объем кода - хорошо.
Но то, что в процессе вы еще убрали параметры из функций проверки для фигур, - плохо. Основной принцип разработки функций - они должны быть независимыми от окружения. Для этого все их входные данные должны поступать через параметры, выходные - аналогично. То есть, вот так было правильно:

    int king(char word1, char word2, int num1, int num2)

А вот так нет:

    int king()

2019-09-22 11:39 UTC, fyrirvari commented
Хорошо, я учту. Сейчас приведу к нужному виду.

2019-09-22 13:30 UTC, alvls commented
Отлично!

2019-09-28 20:55 UTC, merged