task0
alvls/mp1-2019-2 pull request #17
Opened 2019-09-21 08:56 UTC by samburovam

2019-09-21 09:54 UTC, alvls requested changes

2019-09-21 09:54 UTC, alvls commented on samburova_mi/task0/Source.cpp
> +		scanf_s ("%f %f %f %f", &x1, &y1, &x2, &y2);
Начиная с этой строки весь код излишне сдвинут вправо. Исправьте.

2019-09-21 09:54 UTC, alvls commented on samburova_mi/task0/Source.cpp
> +		scanf_s ("%f %f %f %f", &x1, &y1, &x2, &y2);
Для типа double нужно использовать формат ввода %lf, а не %f. Исправьте здесь и ниже.

2019-09-21 09:54 UTC, alvls commented on samburova_mi/task0/Source.cpp
> +		else if ((r1 == r2) && (q == 0)) printf ("���������� ���������");
Исправьте форматирование на 

    else if ((r1 == r2) && (q == 0))
      printf ("Окружности совпадают");

Далее аналогично.

2019-09-21 09:54 UTC, alvls commented on samburova_mi/task0/Source.cpp
> +		else return;
Неверная ветка else. Она приводит к тому, что часть ситуаций не будет обработана. Например, при таком вводе:
0 0 5 0 
3 1
результат должен быть - "окружности находятся на достаточном расстоянии друг от друга". Но вы его не получите.

2019-09-21 09:54 UTC, alvls commented
Маргарита, исправьте замечания, снова сделайте коммит и пуш.

2019-09-22 16:35 UTC, samburovam commented
Здравствуйте, у меня никак не заработает пуш. 


>Суббота, 21 сентября 2019, 12:54 +03:00 от Alexander Sysoyev <notifications@github.com>:
>
>Маргарита, исправьте замечания, снова сделайте коммит и пуш.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Рита Самбурова

#include <stdio.h>
#include "math.h"
#include "locale.h"
void main()
{
	double r1, r2, a, q, x1, y1, x2, y2;
	setlocale(LC_ALL, "Russian");
	printf ("Введите координаты центров окружностей");
	scanf_s ("%lf %lf %lf %lf", &x1, &y1, &x2, &y2);
	q = sqrt(pow((x2 - x1), 2) + pow((y2 - y1), 2));
	printf ("Введите радиусы окружностей");
	scanf_s ("%f %f", &r1, &r2);
	if (r2 > r1)
	{
		a = r1;
		r1 = r2;
		r2 = a;
	}
	if ((r1 == r2) && (q == 0))
	 printf ("Окружности совпадают");
	else if (q == 0)
	 printf ("Одна окружность находится внутри другой и их центры совпадают");
	else return;

	if ((q < r1) && (r1 > 2 * r2))
	 printf ("Малая окружность находится внутри большой");
	else if (q == r1) 
	 printf ("Центр малой окружности лежит на большой");
	else if ((q > r1) && (q < r1 + r2))
	 printf ("Малая окружность пересекает большую в 2 точках и меньшая ее часть лежит внутри большой");
	else if ((q < r1) && (q + r2 > r1)) 
	 printf ("Малая окружность пересекает большую в 2 точках и большая ее часть лежит внутри большой");
	else if (q == r1 + r2) 
	 printf ("Окружности касаются внешним образом");
	else if (q > r1 + r2)
	 printf("окружности находятся на достаточном расстоянии друг от друга");

		
	scanf_s("%f", &a);
}

2019-09-22 17:51 UTC, alvls commented
Маргарита, что вы имеете ввиду? Вы же сделали первый коммит еще 17 сентября. Делайте аналогично.
Вносите правки. Потом в командной консоли из папки с вашим репозиторием выполняете

    git commit -m "Комментарий к коммиту"
    git push

Если что-то не получается при выполнении psuh, сделайте скриншот и вставьте его сюда, я посмотрю.

2019-09-22 18:11 UTC, samburovam commented
Проблемы с консолью


>Воскресенье, 22 сентября 2019, 20:51 +03:00 от Alexander Sysoyev <notifications@github.com>:
>
>Маргарита, что вы имеете ввиду? Вы же сделали первый коммит еще 17 сентября. Делайте аналогично.
>Вносите правки. Потом в командной консоли из папки с вашим репозиторием выполняете
>git commit -m "Комментарий к коммиту"
>git push
>
>Если что-то не получается при выполнении psuh, сделайте скриншот и вставьте его сюда, я посмотрю.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
� ита Самбурова

2019-09-22 18:30 UTC, alvls commented
Где скриншот?

2019-09-22 18:33 UTC, samburovam commented
![11](https://user-images.githubusercontent.com/55128869/65392710-500b9700-dd80-11e9-887b-4e92db29f344.png)
![12](https://user-images.githubusercontent.com/55128869/65392714-5437b480-dd80-11e9-8f44-549c6e9f6c01.png)

2019-09-22 18:57 UTC, alvls commented
Это не консоль. Это Блокнот. В Проводнике (см. ваш первый скриншот) выделяете строку с адресом и набираете в ней cmd. Должна запуститься командная консоль. В ней и нужно набирать команды git.

2019-09-22 19:15 UTC, samburovam commented
Странно, в прошлый раз именно там и была консоль. В этот раз, вроде, получилось

2019-09-22 19:20 UTC, alvls commented
С выравниваем все равно проблемы. Выполните команду в меню Правка -> Дополнительно -> Форматировать документ

2019-09-22 19:24 UTC, samburovam commented
Готово

2019-09-22 19:27 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Качество кода: | 1,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 1,0

2019-09-22 19:27 UTC, merged