Task1
alvls/mp1-2019-2 pull request #26
Opened 2019-09-27 09:46 UTC by NASYA1610

2019-09-27 11:21 UTC, alvls requested changes

2019-09-27 11:21 UTC, alvls commented on plenkova_ad/task1/Source.cpp
> +	scanf_s("%f", &d);
Нет проверок на введенные данные (см. постановку задачи).

2019-09-27 22:30 UTC, NASYA1610 commented
Программу поправила, но у меня git push не работает теперь...
![изображение](https://user-images.githubusercontent.com/53973961/65805679-2cd15500-e18f-11e9-87b6-9e5fcea2591d.png)

2019-09-28 05:42 UTC, alvls commented
Вы пытаетесь сделать пуш в мой репозиторий, а должны делать в свой. Видимо, вы клонировали себе не ваш форк, а мой репозиторий. В него вы ничего «запушить» не сможете.

 

С уважением,

Александр Сысоев,

доцент кафедры МОСТ

институт ИТММ

ННГУ им. Н.И. Лобачевского

 

From: NASYA1610 [mailto:notifications@github.com] 
Sent: Saturday, September 28, 2019 1:30 AM
To: alvls/mp1-2019-2 <mp1-2019-2@noreply.github.com>
Cc: Alexander Sysoyev <sysoyev@vmk.unn.ru>; Comment <comment@noreply.github.com>
Subject: Re: [alvls/mp1-2019-2] Task1 (#26)

 

Программу поправила, но у меня git push не работает теперь...
 <https://user-images.githubusercontent.com/53973961/65805679-2cd15500-e18f-11e9-87b6-9e5fcea2591d.png> 

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub <https://github.com/alvls/mp1-2019-2/pull/26?email_source=notifications&email_token=ABJSQNBZB3AEGHYNIVPW7BLQL2CP3A5CNFSM4I3EHG4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72HXHY#issuecomment-536116127> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ABJSQNFQDT7ELOODFH7V7DTQL2CP3ANCNFSM4I3EHG4A> .  <https://github.com/notifications/beacon/ABJSQNDEPMAB4F2UDH42WUTQL2CP3A5CNFSM4I3EHG4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72HXHY.gif>

2019-09-28 21:55 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2019-09-28 21:55 UTC, merged