task1
alvls/mp1-2019-2 pull request #27
Opened 2019-09-27 14:00 UTC by golovtwo

2019-09-28 22:10 UTC, alvls commented
Проверять код, размещенный другим человеком, я не буду.

2019-09-29 05:51 UTC, golovtwo commented
Здравствуйте, этот код выкладывала я. Просто на той неделе задачу 0 с моего ноутбука выкладывал Никита Головкин, и почему-то в этот раз мой код выложился от его имени, я этого не заметила. Сейчас отправлено от моего имени. Извините, что так вышло.

2019-09-29 16:56 UTC, alvls requested changes

2019-09-29 16:56 UTC, alvls commented on strebkova_ko/task1/Source.c
> +##include <locale.h>
Лишний символ #

2019-09-29 16:56 UTC, alvls commented on strebkova_ko/task1/Source.c
> +include <stdio.h>
Не хватает символа #

2019-09-29 16:56 UTC, alvls commented on strebkova_ko/task1/Source.c
> +double h, w, d, mBWalls, mWalls, mCapps, mShelfs, mDoors, M;
Исправьте выравнивание кода в функции main

2019-09-29 17:11 UTC, golovtwo commented
Исправила

2019-09-29 17:31 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2019-09-29 17:31 UTC, merged