Task 1
alvls/mp1-2019-2 pull request #29
Opened 2019-09-28 15:52 UTC by Jul-Jak

task 1

2019-09-28 22:14 UTC, alvls requested changes

2019-09-28 22:14 UTC, alvls commented on jakovleva_ju/task1/Source.cpp
> +	printf("vvedite h,w,d\n");
Неплохо бы указать, в каких единицах нужно вводить данные

2019-09-28 22:14 UTC, alvls commented on jakovleva_ju/task1/Source.cpp
> +		printf("%.3lf\n", M);
Неплохо бы вывести, в каких единицах получен ответ.

2019-09-29 16:48 UTC, alvls requested changes

2019-09-29 16:48 UTC, alvls commented on jakovleva_ju/task1/Source.cpp
> +	printf("vvedite h,w,d v kilogrammah\n");
Серьезно? Высота и прочее в килограммах? :)

2019-09-29 17:30 UTC, Jul-Jak commented
Сейчас исправлю, я даже не заметила -------- Исходное сообщение --------Тема: Re: [alvls/mp1-2019-2] Task 1 (#29)От: Alexander Sysoyev Кому: alvls/mp1-2019-2 Копия: Jul-Jak ,Author @alvls requested changes on this pull request.







In jakovleva_ju/task1/Source.cpp:

> @@ -9,12 +9,13 @@ int main(void)

 	double p3 = 850;

 

 	double h, w, d, M;

-	printf("vvedite h,w,d\n");

+	printf("vvedite h,w,d v kilogrammah\n");



Серьезно? Высота и прочее в килограммах? :)



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/alvls/mp1-2019-2/pull/29?email_source=notifications\u0026email_token=ANETIHMWBIPHT563WTVHDC3QMDL5FA5CNFSM4I3OU3KKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGIKITA#pullrequestreview-294691916",

"url": "https://github.com/alvls/mp1-2019-2/pull/29?email_source=notifications\u0026email_token=ANETIHMWBIPHT563WTVHDC3QMDL5FA5CNFSM4I3OU3KKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGIKITA#pullrequestreview-294691916",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

2019-09-29 17:40 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2019-09-29 17:40 UTC, merged