Task 1
alvls/mp1-2019-2 pull request #32
Opened 2019-09-30 09:32 UTC by samburovam

2019-09-30 11:17 UTC, alvls commented
Маргарита, вы не добавили файл с исходным кодом в проект task1. Или не выложили файл проекта на гитхаб. Исправьте.

2019-09-30 11:56 UTC, samburovam commented
Добавила

2019-09-30 12:31 UTC, alvls requested changes

2019-09-30 12:31 UTC, alvls commented on samburova_mi/task1/Source.cpp
> +	scanf_s("%lf, %lf, %lf" & h, &w, &d);
Исправьте на &h - пробела здесь быть не должно.

2019-09-30 12:31 UTC, alvls commented on samburova_mi/task1/Source.cpp
> +	if ((h >= 0, 18) && (h <= 0, 22) && (w >= 0, 08) && (w <= 0, 12) && (d >= 0, 05) && (d <= 0, 09))
Все эти числа должны быть записаны в виде 0.18 (через точку и без пробелов после точки).

2019-10-01 07:36 UTC, alvls requested changes

2019-10-01 07:36 UTC, alvls commented on samburova_mi/task1/Source.cpp
> +	scanf_s("%lf, %lf, %lf" &h, &w, &d);
Не хватает запятой после "

2019-10-01 07:36 UTC, alvls commented on samburova_mi/task1/Source.cpp
> +#define DWP 820;
При объявлении констант через define нельзя ставить ;
Исправьте здесь и ниже.

2019-10-03 05:36 UTC, alvls commented on samburova_mi/task1/Source.cpp
> +	if ((h >= 0.18) && (h <= 0.22) && (w >= 0.08) && (w <= 0.12) && (d >= 0.05) && (d <= 0.09))
Все ограничения на размер нужно умножить на 10

2019-10-03 05:37 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,7
Качество проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,7

2019-10-03 05:37 UTC, merged