Task 2
alvls/mp1-2019-2 pull request #36
Opened 2019-10-01 07:49 UTC by maxkost

2019-10-05 06:00 UTC, alvls commented
Максим, файл test.c в проекте task2 не открывается.

2019-10-05 08:24 UTC, maxkost commented
Это лишний файл, я его удалил в последнем коммите

2019-10-05 08:29 UTC, maxkost commented
Забыл его убрать из проекта в VS.
Исправил

2019-10-07 16:48 UTC, alvls requested changes

2019-10-07 16:48 UTC, alvls commented on kostyukov_mi/task2/Source.c
> +}
Добавьте пустую строку перед следующей функцией

2019-10-07 16:48 UTC, alvls commented on kostyukov_mi/task2/Source.c
> +		if ( (c1 == '>') || (c2 == '>') )
Единообразно расставьте пробелы по тексту программы

2019-10-07 16:48 UTC, alvls commented on kostyukov_mi/task2/Source.c
> +	int r;
Перенесите объявление в начало функции

2019-10-07 20:00 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 6,2

2019-10-07 20:04 UTC, maxkost commented
Есть ли возможность досдать таск 2' с учетом "подвоха" завтра для получения доп. баллов?

2019-10-07 20:09 UTC, alvls commented
Можете попробовать. Но доп. баллы я не гарантирую. Все будет зависеть от того, насколько мне понравится ваше решение.

2019-10-07 20:11 UTC, maxkost commented
Чтож, буду стараться!

2019-10-11 09:18 UTC, merged