task 2
alvls/mp1-2019-2 pull request #48
Opened 2019-10-05 19:01 UTC by dariabnn

Вроде как все получилось, но мне не нравится один момент: во 2 режиме программы в самом конце, когда пользователь  выбирает "=" вместе с завершением программы появляется надпись: " Вы допустили ошибку при выборе режима программы, пожалуйста, попробуйте еще раз", у меня есть подозрение, что это из-за того, что есть два default. И это можно как-то убрать или для этого обязательно нужно будет что-то переписывать через конструкцию if и тд?

2019-10-06 09:15 UTC, alvls requested changes

2019-10-06 09:15 UTC, alvls commented on zaytseva_da/task2/task2.c
> +	default:
Не хватает оператора break перед этим default:

2019-10-06 09:17 UTC, alvls commented
Дарья, чтобы избавиться от проблемы, о которой вы пишите, нужен еще один break (см. комментарий к коду).

2019-10-06 09:20 UTC, alvls requested changes

2019-10-06 09:20 UTC, alvls commented on zaytseva_da/task2/task2.c
> +
Лишняя пустая строка

2019-10-06 09:20 UTC, alvls commented on zaytseva_da/task2/task2.c
> +
Лишние пустые строки

2019-10-06 20:18 UTC, dariabnn commented
Да, точно, из-за невнимательности забыла. Спасибо за подсказку!

2019-10-07 17:10 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2019-10-08 07:32 UTC, merged