Task5, но это не точно))
alvls/mp1-2019-2 pull request #89
Opened 2019-11-24 15:04 UTC by AnasteishA-1610

2019-11-24 15:05 UTC, AnasteishA-1610 commented
Можно ли как-то обойтись без struct чтобы была связь между названиями файлов и их размером, а то у меня размер сортируется, а когда вывожу, названия не так как надо

2019-11-24 15:42 UTC, alvls commented
Можно использовать два отдельных массива и сортировать сразу оба.

2019-11-24 18:33 UTC, AnasteishA-1610 commented
Но file.name это же тип char, такой массив разве будет сортироваться параллельно с int?

2019-11-24 19:41 UTC, alvls commented
Как реализуете, так и будет.

2019-11-27 20:37 UTC, alvls commented
Программа не компилируется.
Если исправить ошибки, то вот что получается при повторной сортировке:
```
Время сортировки = 0,000000
Хотите отсортировать ещё раз? да - 1, нет - 0
1

Отсортировать по возрастанию - 1, по убыванию - 2
2

Выберите тип сортировки:
Сортировка Пузырьком 1
Сортировка Выбором 2
Сортировка Вставками 3
Сортировка Слиянием 4
Сортировка Хоара(Быстрая сортировка) 5
Сортировка Шелла 6
Сортировка подсчётом 7
2

count of files: 52
FILE               SIZE
----               ----
ММММММММММММ  -858993460
```

2019-11-28 07:32 UTC, AnasteishA-1610 commented
Если сегодня исправлю, штрафные баллы будут?

2019-11-28 07:41 UTC, alvls commented
> 
> Если сегодня исправлю, штрафные баллы будут?

Если сегодня, не будут.

2019-11-28 10:48 UTC, alvls requested changes

2019-11-28 10:48 UTC, alvls commented on plenkova_ad/task5/Source.c
> +	gets_s(path);
Не хватает параметра у функции.

2019-11-28 10:48 UTC, alvls commented on plenkova_ad/task5/Source.c
> +			tt = float(t2 - t1) / CLOCKS_PER_SEC;
Неверная запись. Должно быть так:
`tt = (float)(t2 - t1) / CLOCKS_PER_SEC;`

2019-11-28 10:48 UTC, alvls commented
Анастасия, код все еще не собирается. Исправьте ошибки.

2019-11-28 12:57 UTC, alvls commented
Продвинулись дальше.
Теперь на папках с малым числом файлов работает, но на c:\windows\system32 падает.

2019-11-28 14:35 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 6,0
Качество   проектирования: | 3,0
Качество кода: | 3,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 12,0

2019-11-28 14:35 UTC, merged